name: Strapi CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Docker image (Strapi is built INSIDE Dockerfile)
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/strapi:latest .

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi:latest

      # Deploy on server
      - name: Deploy to Server (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/strapi:latest
            docker stop strapi || true
            docker rm strapi || true
            docker run -d \
              --name strapi \
              -p 1337:1337 \
              ${{ secrets.DOCKER_USERNAME }}/strapi:latest
